### ISSUE TITLE
const mn = bip39.generateMnemonic(wordlist)

### ISSUE THREAD

**Issue by Unchain68** [paulmillr/scure-bip39#10]
I can't make a mnemonic example like readme file.

![image](https://user-images.githubusercontent.com/109026317/193585422-087ec26b-cc83-4568-835b-437a865c1fec.png)

But, this works.

**Comment by Unchain68** [comment]
Other examples of readme also don't work like readme file.

**Comment by paulmillr** [comment]
import { wordlist } from '@scure/bip39/wordlists/english';

See it's {wordlist} which uses destructive assignment. Since you are not using it, you are not following readme example in full

**Comment by Unchain68** [comment]
Thank you very much,  it's my mistake.
