### ISSUE TITLE
randomBytes error React Native

### ISSUE THREAD

**Issue by Skarsh** [paulmillr/scure-bip39#12]
Hello! 
I am getting an error when I try to use this package on React Native 0.7 generating the mnemonic seed: 
![image](https://user-images.githubusercontent.com/12898765/204150067-d69444c5-0222-4b65-bd3b-9940d85406e1.png)
Using react-native-random-bytes instead of the one provided with the package kinda solves the issue, but that's of course
something I really don't want to do.

Am I missing something obvious here? :sweat_smile:

**Comment by paulmillr** [comment]
Nothing you're missing. Use the package.
