### ISSUE TITLE
Convert to ESM.

### ISSUE THREAD

**Issue by MicahZoltu** [paulmillr/scure-bip39#14]
NodeJS now supports ES Modules, as well as all browsers.  Currently, this package doesn't work natively in a browser without some extra bundling/transpiling step and it would be nice if it was brought up to date with modern best practices by distributing it as an ES Module.

Note: I believe I have spoken with you about this in other places, but I wanted to get an issue filed for tracking (and so I stop trying to use this package only to remember why I had to drop it previously!)

**Comment by paulmillr** [comment]
Just a quick heads up on this:

1. The pkg won't work in browsers w/o transpilation even if it'll be pure ESM. Reason: https://github.com/paulmillr/noble-hashes/blob/8f6d0573f68445cc75df488cf8d20a2a25691c1d/src/utils.ts#L3
2. I see no point in adding a hybrid module that will simply increase pkg size 2x
3. As soon as scure will work in browsers w/o transpilation i'd be pushing upgrade to pure-ESM

Will revisit the issue later this year

**Comment by MicahZoltu** [comment]
Hmm, why does `import { crypto } from '@noble/hashes/crypto';` in noble-hashes cause a problem in browsers?  Looking at `@noble/hashes/crypto`, in a browser it will just return `globalThis.crypto` which should work fine...
```ts
declare const globalThis: Record<string, any> | undefined;
export const crypto = typeof globalThis === 'object' && 'crypto' in globalThis ? globalThis.crypto : undefined;
```

**Comment by paulmillr** [comment]
because path `'@noble/hashes/crypto'` is invalid and nonsensical for a browser. Browser needs full URL or at least relative url, not "npm package namespace".

**Comment by paulmillr** [comment]
Import maps are not supported "in all modern browsers": https://caniuse.com/import-maps - it is only 74.54%. For comparison, Bigints are 94.28%.

**Comment by paulmillr** [comment]
We aren't making software for a bunch of people, we are making software for everyone; and if everyone switches to it, it will increase security of the whole ecosystem, which is a huge gain.

This requires compromises.

**Comment by paulmillr** [comment]
1.2.1 makes the package hybrid and adds ESM support, so will close this for now.

Removing common.js support would take 1.5 years or more: we need to wait until node.js v18 goes out of fashion.
