### ISSUE TITLE
Expected Uint8Array - React Native

### ISSUE THREAD

**Issue by earthgohan** [paulmillr/scure-bip39#7]
Great library!

But in react native, its giving the following error.

when 

```
const mn = bip39.generateMnemonic(wordlist);
console.log(mn);
```

![Simulator Screen Shot - iPhone 12 Pro - 2022-07-31 at 21 00 15](https://user-images.githubusercontent.com/85003405/182034102-8714783d-3838-4e10-9a7e-e48452fb11b2.png)

**Comment by earthgohan** [comment]
working after polyfill of https://www.npmjs.com/package/react-native-crypto

**Comment by paulmillr** [comment]
We don't use any "crypto". So, what are you polyfilling witht his module?

**Comment by earthgohan** [comment]
crypto is used here -> https://github.com/paulmillr/noble-hashes/blob/8b0fb5fb9485393df2896d380643a978de8714cf/src/utils.ts#L5

**Comment by paulmillr** [comment]
No, it is not using crypto in non-nodejs environments. Read the comment above this line. 

If your bundler/builder thinks it's using crypto, report it to the bundler's repository.
