### ISSUE TITLE
Can we override the random source?

### ISSUE THREAD

**Issue by CMCDragonkai** [paulmillr/scure-bip39#9]
The official bip39 in JS supports overriding the random source. Can we override it here too?

This can help use this library in environments where neither node crypto nor webcrypto is available.

**Comment by CMCDragonkai** [comment]
Right now I'm doing something like this:

```
// @ts-ignore - this overrides the random source used by @noble and @scure libraries
utils.randomBytes = (size: number = 32) => getRandomBytesSync(size);
```

**Comment by paulmillr** [comment]
No. Not planned. This is easy path to backdoors.
